### ISSUE TITLE
How do I change the safemode?

### ISSUE THREAD

**Issue by muhuk** [asciidoctor/asciidoctor-lein-plugin#2]
This snippet displays `SafeMode: SECURE`:

```
ifdef::safe-mode-unsafe[]
SafeMode: UNSAFE
endif::safe-mode-unsafe[]

ifdef::safe-mode-safe[]
SafeMode: SAFE
endif::safe-mode-safe[]

ifdef::safe-mode-server[]
SafeMode: SERVER
endif::safe-mode-server[]

ifdef::safe-mode-secure[]
SafeMode: SECURE
endif::safe-mode-secure[]
```

It says [here](http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely) this is the default mode:

```
Asciidoctor and trusted extensions may still be allowed to embed trusted content
into the document. This is the default safe mode for the API. Its integer value is 20.
```

I would like to run in `UNSAFE` mode. I couldn't find it in the configuration parameters. How I can configure it so?

Also I'd classify this as CLI, so I think it should be `UNSAFE` by default.

**Comment by mojavelinux** [comment]
The plugin doesn't seem to support this option currently. (Meaning it's not being passed through). It should be an option that is adjacent to the `in_place` option as seen on this line:

https://github.com/asciidoctor/asciidoctor-lein-plugin/blob/master/src/lein_asciidoctor/core.clj#L106

Perhaps you could consider adding support for it. It's fine to pass the value as a lower-case string (e.g., "safe"). Asciidoctor will make sense of the value.

> Also I'd classify this as CLI, so I think it should be UNSAFE by default.

I tend to agree. That's what the other plugins do. I'm pretty sure the Gradle and Maven plugins use UNSAFE by default, but it's worth verifying.

**Comment by vbauer** [comment]
I've just added new parameter `:safe`. I hope it will resolve current problem.

**Comment by muhuk** [comment]
Thanks @vbauer, I can confirm it works.

It didn't solve my problem though. I was trying to include a file containing an HTML snippet (`<script>`), it was being escaped. So I ended up using `++++`.

**Comment by mojavelinux** [comment]
> Thanks @vbauer, I can confirm it works.

:+1: 

> It didn't solve my problem though.

Sometimes we solve an issue as a side effect of another issue. However it happens, we'll take it.

> I was trying to include a file containing an HTML snippet (<script>), it was being escaped. So I ended up using ++++.

That's one way of doing it. The solution I recommend, however, is to use a docinfo file. The docinfo files allow you to append additional HTML to the top or bottom of the converted document.
